version: '3.8'

services:
  livesup:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/livesup
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: livesup
      PGPORT: 5432
      PGHOST: db
      MIX_ENV: prod
    # env_file:
    #   - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"