{
 "title": "LiveSup - Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Prometheus Job",
    "query": {
     "query": "label_values(live_sup_prom_ex_prom_ex_status_info, job)"
    }
   },
   {
    "name": "instance",
    "label": "Application Instance",
    "query": {
     "query": "label_values(live_sup_prom_ex_prom_ex_status_info, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "15s, 30s, 1m, 5m, 15m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Environment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "live_sup_init_info{}", "legendFormat": "Environment" }
   ]
  },
  {
   "title": "LiveSup Started",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 0 },
   "targets": [
    { "expr": "live_sup_init_info" }
   ]
  },
  {
   "title": "Number of Calls to Datasources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(live_sup_build_data_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", datasource_name=~\".+\"}[$interval])) by(datasource_name)",
     "legendFormat": "{{ datasource_name }}"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "stat",
   "description": "The number of running BEAM processes currently running.",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "live_sup_prom_ex_beam_stats_process_count{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average Execution Time",
   "type": "graph",
   "description": "The average time it took to build data",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(live_sup_build_data_duration_milliseconds_sum{job=\"$job\", instance=\"$instance\", name=~\".+\"}[$interval])) by(name, datasource_name) / sum(irate(live_sup_build_data_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", name=~\".+\"}[$interval])) by(name, datasource_name)",
     "legendFormat": "{{ name }} - {{ datasource_name }}"
    }
   ]
  }
 ]
}