# Global Configurations
global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'elixir_sample_app'

# Targets to scrape
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['docker.for.mac.localhost:9090']

  - job_name: 'live_sup'
    static_configs:
      - targets: ['docker.for.mac.localhost:4000']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['docker.for.mac.localhost:9187']
